### ISSUE TITLE
MissionsPanel (Auftragsliste) realisieren

### ISSUE THREAD

**Issue by EduardDopler** [davidbecher/SEPRescue#11]
Die Auftragsliste in der Sidebar implementieren und eine Möglichkeit zum Abschließen von Aufträgen hinzufügen.
Spalten der Tabelle sind:

Status | (ID) Standort | Pers. | Sani. | Art
:------:|:------------- | -----:| -----:| ---
[grün] | (37) Essen-West | 2 | 2 | NF
[gelb] | (38) Essen-Nord | 3 | 2 | C2
[gelb] | (39) Essen-Nord | 3 | 2 | NF
[rot] | (40) Altstadt | 5 | 3 | NF

Wobei die Statusspalte den Zuständen *zurückgekehrt*, *aktiv* oder *eingereiht* entspricht.
Das Abschließen von Aufträgen soll laut Aufgabenblatt nur für zurückgekehrte Teams möglich sein.

**Comment by EduardDopler** [comment]
Die Tabelle arbeitet bereits gut mit dem Erstellen von Aufträgen (#13) zusammen. Es fehlt noch das Abschließen von Aufträgen über die DONE-Buttons. 
Der done-all Button soll (als Observer über die update-Methode) aktiviert werden, wenn mindestens ein Auftrag den Status FINISHED hat. Sein ActionListener soll dann removeMission für alle FINISHED-Aufträge aufrufen können. 
Der done Button wird aktiviert, wenn ein Auftrag in der Tabelle ausgewählt wird, der FINISHED ist. Sein ActionListener ruft dann removeMission für diesen Auftrag auf.

**Comment by davidbecher** [comment]
Ich mache daraus mal ein eigenes Issue. Damit die Issues nicht alle zu groß werden und zu viel umfassen.
