### ISSUE TITLE
Simulator: Flugbahn berechnen/simulieren

### ISSUE THREAD

**Issue by EduardDopler** [davidbecher/SEPRescue#23]
Der Simulator soll aus den Daten `baseLocation` (aus *IUserSettings* lesbar), `destLat` und `destLong` (aus der jeweiligen *Mission*) und ggf. aus Hubschrauber-Eigenschaften wie Geschwindigkeit (bisher nicht implementiert) eine Flugbahn simulieren und "kontinuierlich" (i.S.v. alle *x* ms) die `currentLocation` des Hubschraubers aktualisieren.
Nach einem definierten Kriterium — z.B. Hubschrauber ist wieder an der `baseLocation` — soll `finishMission()` in der Auftragsverwaltung aufgerufen werden.
Um erst einmal keine anderen Klassen verändern zu müssen, wäre es hilfreich, wenn die Klasse Simulator zum Testen erst einmal autonom arbeitet und fake Werte definiert. Falls möglich, sollte die neue Position vom Typ `org.jxmapviewer.viewer.GeoPosition` sein.
Noch später können wir über Threads nachdenken und unser Concurrency-Wissen einfließen lassen ;)

**Comment by R-Heger** [comment]
Die grundlegenden Funktionen sind implementiert. Alles weitere fällt unters Gold Plaiting.
