### ISSUE TITLE
this.* -Referenz konsequent verwenden

### ISSUE THREAD

**Issue by R-Heger** [davidbecher/SEPRescue#3]

**Comment by EduardDopler** [comment]
Wurde noch nicht konsequent umgesetzt.
Ich glaube, Roman war noch nicht fertig.
Zum Beispiel:
```
private void setPoolCapacity(int i) {
        poolCapacity = i;
        this.setChanged();
        this.notifyObservers(POOL_STATUS_CHANGED);
    }

    @Override
    public int getCurrentSize() {
        return paramedics.size();
    }

    @Override
    public void increaseCapacity(int number) {
        for (int i = 0; i < number; i++) {
            paramedics.add(new Paramedic());
            this.setPoolCapacity(getPoolCapacity() + number);
        }
    }
```
(hier fehlen z.B. die *this* vor poolCapacity und paramedics (2x))
Außerdem in ResourceManagement, ResourcePanel, SidebarPanel etc.

**Comment by EduardDopler** [comment]
Wenn man es andererseits wirklich überall umsetzt, ist der ganze Code voll *this*...

**Comment by davidbecher** [comment]
Ich habe mir den Code auch gerade mal angeschaut... Ich finde auch, dass bei absolut konsequentem Durchziehen von **this** der Code ganz schön aufgebläht wird. Also an allen Stellen, an denen zum Beispiel eine Methode aufgerufen wird.
```
this.setPoolCapacity(this.getPoolCapacity() + number);
```

Alle Methodennamen, die keinen Variablennamen inklusive '.' haben (also nicht sowas wie ```someClassVariable.methodDoSomething()```), sind ja allein dadurch schon erkennbar. mMn ist dort dann das this schon eher redundant.
Wäre tatsächlich auch dafür, dass man es dann wirklich nur nutzt, wenn ein Namenkonflikt entsteht (http://docs.oracle.com/javase/tutorial/java/javaOO/thiskey.html).
