### ISSUE TITLE
Spezifische Getter in IUserSettings statt Rückgabe der HashTable

### ISSUE THREAD

**Issue by EduardDopler** [davidbecher/SEPRescue#35]
Fällt sicherlich unter die Kategorie *Code-Schönheit*, aber könnte auch die Code-*Sicherheit* erhöhen:
Statt
`getSettings().getManagement().get(IUserSettings.MANAGEMENT_SEARCH_RADIUS)`
würde
`getSettings().getSearchRadius()`
dafür sorgen, dass man an der aufrufenden Stelle nicht die HashTable bekommt, sondern nur den Wert, den man benötigt. Das verhindert auch, dass man dort an dem Datenspeicher selbst herumwerkeln kann.
Danach könnte man die Konstanten wahrscheinlich auch private schalten und nur noch in der Klasse selbst benutzen.
Was meinst du, @davidbecher, wäre das mit der Implementation vom ManagementSettingsController vereinbar?

**Comment by davidbecher** [comment]
Würde ich umsetzen, wenn das in Ordnung ist. Ich würde sogar soweit gehen und sagen, wir sollten einzelne setter haben für die anderen Einstellungen. Die aktuelle Methode `updateManagement()` verlangt ja, dass man alle Parameter übergibt, was ja je nach GUI (Model soll ja unabhängig von GUI sein) vielleicht gar nicht wünschenswert ist, weil man eventuell Dinge einzeln updaten will.

**Comment by EduardDopler** [comment]
Hab ich auch überlegt, wollte aber nicht alles umschmeißen, nur das Setzen für unseren Fall (alles auf einmal) überarbeiten. Aber gut, dass du das machst  :+1: 
Nur finde ich, dass danach auch weiterhin das updaten der Einstellung(en) und das persistente Speichern derselben getrennt sein sollte.
