### ISSUE TITLE
Bugfix : Serialization beim Zoomen

### ISSUE THREAD

**Issue by R-Heger** [davidbecher/SEPRescue#41]
Beim Neustart des Programms (also nachdem es bereits einmal ausgeführt wurde) wird der Zoom nicht korrekt gesetzt.

**Comment by EduardDopler** [comment]
Ich weiß nicht, wie weit du bist, aber ich habe mehr oder weniger beiläufig Folgendes festgestellt (wenn das jetzt ein Spoiler ist und du es selbst herausfinden möchtest, einfach nicht lesen :wink:):
Das Problem, dass unser `zoomToActionRadius()` beim Start nicht funktioniert, liegt bei JXMapKits `zoomToBestFit()` und dem Zeitpunkt, an dem wir das aufrufen. Es exisitert schlicht noch keine geeignete Fenstergeometrie, anhand die Funktion irgendetwas Brauchbares berechnet kann. Sie muss also aufgerufen werden *nachdem* das Fenster geladen ist. Hier habe ich nun mehrere Ansätze getestet. Es gibt einen EventListener, der feuert, wenn ein JComponent jeglicher Art (also auch unsere Map) oder ein hierarchischer Vorfahre das erste Mal angezeigt wird: `ancestorAdded()` vom *AncestorListener*. Fügt man den also zur Map (bzw. über dessen Controller blablubb) hinzu und ruft beim Auftritt des Events `zoomToActionRadius()` auf, wird ganz gut gezoomt.
Aber. Leider tritt das Event anscheinend, zumindest bei mir und meinem Window Manager, irgendwann ein, wenn das Fenster noch nicht maximiert ist (komisch, ich weiß, weil wir das ja eigentlich schon einstellen, bevor das Fenster sichtbar wird). Das heißt, der Zoom Level passt zu dem nicht maximierten Fenster, sprich: Es ist nicht nah genug heran gezoomt.
Das könnte man als Feature bezeichnen (Überblick und so), könnte man aber vielleicht auch noch anders lösen. So gibt es z.B. noch einen WindowStateListener, der beim Event "Fenster wurde maximiert" auslöst... Das wäre allerdings nur über ganz schön viele Ecken (=Controller) implementierbar.
Also wenn wir nichts Besseres finden, würde ich o.g. Weg vorschlagen; das Ergebnis ist damit schon ganz gut.
Was meint ihr, @R-Heger und @davidbecher?


Quick and Dirty ist das Ganze testbar, wenn am Ende des Konstruktors vom *MapDrawerPanel* Folgendes hinzugefügt wird:
```
        jXMapKit.addAncestorListener(new AncestorListener() {

            @Override
            public void ancestorRemoved(AncestorEvent event) {}

            @Override
            public void ancestorMoved(AncestorEvent event) {}

            @Override
            public void ancestorAdded(AncestorEvent event) {
                System.out.println("mapkit visible, zoom now");
                zoomToActionRadius();
            }
        });
```
