### ISSUE TITLE
Für Textboxen (wie Auftragsort) einen "Hint" anzeigen

### ISSUE THREAD

**Issue by EduardDopler** [davidbecher/SEPRescue#9]
Ein Hint ist ein ausgegrauter Beispieltext, der beim Aktivieren der Textbox verschwindet (oder sobald man den ersten Buchstaben eingibt). Verlässt man die Komponente wieder (oder löscht man alle selbst eingegeben Zeichen), erscheint wieder der Beispieltext. Das wäre z.B. für den Auftragsort sinnvoll, um das Pattern für eine gültige Eingabe anzuzeigen.

**Bsp:**
![hint](https://cloud.githubusercontent.com/assets/9469003/7901773/f1df44c6-0799-11e5-9be1-2cb18d181514.png)

**Comment by EduardDopler** [comment]
Jetzt mal rein logisch gesehen. Eine Frage an die MVC-Experten.
Ich hätte sowas jetzt in einer neuen Klasse umgesetzt, die von *JTextField* erbt, wo ich die Methoden `focusLost()` und `focusGained()` überschreiben würde. Diese Klasse müsste dann also das Interface *FocusListener* implementieren. Darf ich das in einer View-Komponente laut MVC? Andererseits wäre es sehr aufwending, wenn man das über einen Controller laufen lassen würde :-/

(Wenn man es nicht über den Fokus, sondern über das Beginnen des Tippvorgangs laufen lässt, wäre die Methode eben `keyPressed()` und das Interface *KeyListener*.)

**Comment by davidbecher** [comment]
Ich habe es jetzt mal nicht über einen Controller gelöst, weil meiner Meinung nach das Verhalten mit zum Teil der GUI gehört bzw. auch gar keine Kommunikation mit dem unterliegenden Model stattfinden muss. Aber das können wir ja gerne mal beim nächsten Treffen in Erfahrung bringen.

**Comment by davidbecher** [comment]
To Do: HintTextBox auch an anderen Stellen (zum Beispiel im Verwaltungsdialog) umsetzen.
